id: 22
os: iosxr
ansible_password: cisco123
napalm_driver: iosxr_netconf
xr_7: true
dnx: false
management_int: 0/RP0/CPU0/0
max_sid_depth: 6
asn: 65000
bgp_rrc: true
bgp_rr: false
netflow: false
xrd: false

optics:
  - {enable: false}

network_interfaces:
  - {name: HundredGigE0/0/0/0, descr: "ASP - CORE.103", remote_id: 103, vlan: 0, unnumbered: true, igp_inst: ASP_LAB, color: BLUE, igp_metric: 100, te_metric: 120, mtu: 8982}
  - {name: HundredGigE0/0/0/1, descr: "ASP - CORE.101", remote_id: 101, vlan: 0, unnumbered: true, igp_inst: ASP_LAB, color: BLUE, igp_metric: 100, te_metric: 120, mtu: 8982}
  - {name: HundredGigE0/0/0/2, descr: "ASP - PE.21", remote_id: 21, vlan: 0, unnumbered: true, igp_inst: ASP_LAB, color: BLUE, igp_metric: 100, te_metric: 120, mtu: 8982}  
#  - {name: HundredGigE0/0/0/3, descr: "ASP - CE.11", remote_id: 11, vlan: 0, unnumbered: false, igp_inst: ASP_LAB, color: RED, igp_metric: 1000, te_metric: 120, mtu: 8982}
#  - {name: HundredGigE0/0/0/4, descr: "ASP - CE.12", remote_id: 12, vlan: 0, unnumbered: false, igp_inst: ASP_LAB, color: RED, igp_metric: 1000, te_metric: 120, mtu: 8982}

Flex_Algo_Membership: {128, 129, 130}

Flex_Affinity:
  - {interface: Bundle-Ether1000, color: GREEN }

bfd_multipath:
  - {enable: true, location: 0/RP0/CPU0 }

bundle_members:
  - {enable: false}

breakout:
  - {enable: False}

static_routes:
  - {enable: False}

ebgp_peers:
  - { enable: true, ipv4: 10.11.22.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }
  - { enable: true, ipv4: 10.12.22.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }

ibgp_peers:
  - {enable: false}

sr_pce:
  - ip: 1.1.1.51
    v6: fcbb:bb00:51::1
    precedence: 1
  - ip: 1.1.1.52
    v6: fcbb:bb00:52::1
    precedence: 2

route_reflectors:
  - ip: 1.1.1.51
    v6: fcbb:bb00:51::1
    precedence: 1
  - ip: 1.1.1.52
    v6: fcbb:bb00:52::1
    precedence: 2


sr_policy:
  manual:
  # temp disable - issue w !!% Invalid argument: SRV6 policy does not support binding sid behavior: 71
    - { name: TEST_SR_POLICY, color: 100, endpoint: fcbb:bb00:24::1, locator: ASP_LAB, pce: true }
    - { name: POLICY_RED_PLANE, color: 106, endpoint: fcbb:bb00:24::1, locator: ASP_RED_Plane, pce: true }

  odn:
    # - { color: 128, metric_type: igp, pce: false, algo: 128 }
    # - { color: 129, metric_type: igp, pce: false, algo: 129 }
    # - { color: 130, metric_type: latency, pce: false, algo: 130 }

igmp:
  interfaces:

services:
  l2transport_interfaces:
    # - {name: HundredGigE0/0/0/3, descr: "EVPN VPWS P2P POLICY DC1", vlan: 0, rewrite: none }

  l3_interfaces:
    - {name: Loopback128, descr: "ASP BLUE VRF INTERFACE", vlan: 0, ipv4: 10.22.128.1/32, ipv6: '2000::10:22:128:1/128'}
    - {name: Loopback129, descr: "ASP RED VRF INTERFACE", vlan: 0, ipv4: 10.22.129.1/32, ipv6: '2000::10:22:129:1/128'}
    - {name: HundredGigE0/0/0/3, descr: "ASP - CE.11 GRT Interface", vlan: 100, ipv4: 10.11.22.1/31, ipv6: '2001::10:11:22:1/127'}
    - {name: HundredGigE0/0/0/3, descr: "ASP - CE.11 VRF BLUE", vlan: 101, ipv4: 10.11.22.1/31, ipv6: '2001::10:11:22:1/127'}
    - {name: HundredGigE0/0/0/3, descr: "ASP - CE.11 VRF RED", vlan: 102, ipv4: 10.11.22.1/31, ipv6: '2001::10:11:22:1/127'}
    - {name: HundredGigE0/0/0/4, descr: "ASP - CE.12 GRT Interface", vlan: 100, ipv4: 10.12.22.1/31, ipv6: '2001::10:12:22:1/127'}
    - {name: HundredGigE0/0/0/4, descr: "ASP - CE.12 VRF BLUE", vlan: 101, ipv4: 10.12.22.1/31, ipv6: '2001::10:12:22:1/127'}
    - {name: HundredGigE0/0/0/4, descr: "ASP - CE.12 VRF RED", vlan: 102, ipv4: 10.12.22.1/31, ipv6: '2001::10:12:22:1/127'}

  evpn_vpws:
#    - { name: RED_POLICY_DC1_POLICY_DC2, interface: HundredGigE0/0/0/3, evi: 106, sr_policy: POLICY_RED_PLANE }


  l3vpn:
    - name: BLUE
      rd: auto
      vpn_id: 128
      srv6_locator: ASP_BLUE_Plane
      interfaces: 
        - { name: Loopback128 }
        - { name: HundredGigE0/0/0/3.101}
        - { name: HundredGigE0/0/0/4.101}
      bgp_neighbors:
        - { enable: true, ipv4: 10.11.22.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }
        - { enable: true, ipv4: 10.12.22.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }

    - name: RED
      rd: auto
      vpn_id: 129
      srv6_locator: ASP_RED_Plane
      interfaces: 
        - { name: Loopback129 }
        - { name: HundredGigE0/0/0/3.102}
        - { name: HundredGigE0/0/0/4.102}
      bgp_neighbors:
        - { enable: true, ipv4: 10.11.22.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }
        - { enable: true, ipv4: 10.12.22.0, remote_asn: 65100, rp4_in: pass-all, rp4_out: pass-all }

